server:
  port: 8090

spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/todo
  #    username: root
  #    password: root
  #  jpa.hibernate.ddl-auto: create-drop
  #  jpa.show-sql: true
  data:
    cassandra:
      contact-points: 127.0.0.2
      local-datacenter: ybcloud
      keyspace-name: alerts
      schema-action: CREATE_IF_NOT_EXISTS

## Source Database Properties
supplier:
  datasource:
    host: 127.0.0.2
    port: 5433
    database: yugabyte
    username: yugabyte
    password: yugabyte
    streamId: ddb5a797dff546a28c2947233b5aa780
    tableList: public.todo

solace:
  jms:
    host: smf://localhost:55554
    msgVpn: default
    clientUsername: default
    clientPassword: default

target:
  dest: solace-test
