server:
  port: 8090

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/todo
#    username: root
#    password: root
#  jpa.hibernate.ddl-auto: create-drop
#  jpa.show-sql: true
  data:
    cassandra:
      contact-points: 127.0.0.2
      local-datacenter: ybcloud
      keyspace-name: alerts
      schema-action: CREATE_IF_NOT_EXISTS

## Source Database Properties
supplier:
  datasource:
    host: 127.0.0.2
    port: 5433
    database: yugabyte
    username: yugabyte
    password: yugabyte
    streamId: bcd1590f93c944159682a32d84a96b0b
    tableList: public.todo

solace:
  jms:
    host: smf://localhost:55554
    msgVpn: default
    clientUsername: default
    clientPassword: default

target:
  dest: solace-test
